// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UT01325MS3_GYMFEEMANAGEMENT.Data;

#nullable disable

namespace UT01325MS3_GYMFEEMANAGEMENT.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20241120102803_updatedv.0.1")]
    partial class updatedv01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MemberTrainingProgram", b =>
                {
                    b.Property<int>("EnrolledMembersMemberId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramsTrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("EnrolledMembersMemberId", "TrainingProgramsTrainingProgramId");

                    b.HasIndex("TrainingProgramsTrainingProgramId");

                    b.ToTable("MemberTrainingProgram");
                });

            modelBuilder.Entity("UT01325MS3_GYMFEEMANAGEMENT.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("AlertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlertId");

                    b.HasIndex("MemberId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("UT01325MS3_GYMFEEMANAGEMENT.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("UT01325MS3_GYMFEEMANAGEMENT.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("UT01325MS3_GYMFEEMANAGEMENT.Models.TrainingProgram", b =>
                {
                    b.Property<int>("TrainingProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingProgramId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingProgramId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("MemberTrainingProgram", b =>
                {
                    b.HasOne("UT01325MS3_GYMFEEMANAGEMENT.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("EnrolledMembersMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UT01325MS3_GYMFEEMANAGEMENT.Models.TrainingProgram", null)
                        .WithMany()
                        .HasForeignKey("TrainingProgramsTrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UT01325MS3_GYMFEEMANAGEMENT.Models.Alert", b =>
                {
                    b.HasOne("UT01325MS3_GYMFEEMANAGEMENT.Models.Member", "Member")
                        .WithMany("Alerts")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("UT01325MS3_GYMFEEMANAGEMENT.Models.Payment", b =>
                {
                    b.HasOne("UT01325MS3_GYMFEEMANAGEMENT.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("UT01325MS3_GYMFEEMANAGEMENT.Models.Member", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
